-- AlterEnum: 51 materiales nuevos del listado de la empresa.
--
-- Va en su propia migración a propósito. Postgres no deja usar un valor de enum
-- recién agregado dentro de la misma transacción que lo agregó, y Prisma corre
-- cada archivo de migración en una transacción. Por eso el INSERT de los
-- registros de Material vive en la migración siguiente.
--
-- IF NOT EXISTS hace que sea seguro re-ejecutarla sobre una base que ya los tenga.

ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'LASTRE'; -- LASTRE
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ARENA_DE_MAR'; -- ARENA DE MAR
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_67'; -- PIEDRA # 67
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_8_3_8'; -- PIEDRA #8 3/8
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_2_4'; -- PIEDRA 2 -4
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_6'; -- PIEDRA # 6
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'BASE_CLASE_1_A'; -- BASE CLASE 1-A
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'SUB_BASE_CLASE_3'; -- SUB-BASE CLASE 3
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_FILTRANTE'; -- PIEDRA FILTRANTE
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_BOLA_BANCO'; -- PIEDRA BOLA BANCO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ARENA_FINA_LAVADA'; -- ARENA FINA LAVADA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_BOLA_SELECCIONADA'; -- PIEDRA BOLA SELECCIONADA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_FILTRANTE_CAFE'; -- PIEDRA FILTRANTE CAFE
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'MEJORAMIENTO_MTOP'; -- MEJORAMIENTO MTOP
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ARENA_HOMOGENIZADA'; -- ARENA HOMOGENIZADA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ROCARENA'; -- ROCARENA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_6_LAVADA'; -- PIEDRA #6 LAVADA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_7'; -- PIEDRA # 7
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_4_19_38_MM'; -- PIEDRA 4 (19-38 MM)
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_3_8_VSI'; -- PIEDRA 3/8 VSI
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'MATERIAL_DE_MEJORAMIENTO'; -- MATERIAL DE MEJORAMIENTO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'MAT_TRITURADO_PARA_RIPIO'; -- MAT. TRITURADO PARA RIPIO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'BASE_CIUDAD_RODRIGO'; -- BASE CIUDAD RODRIGO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'P_BOLON'; -- P-BOLON
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_1_2_VSI'; -- PIEDRA 1/2 VSI
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'CISCO'; -- CISCO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_ESCOLLERA'; -- PIEDRA ESCOLLERA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'MEZCLA_ASFALTICA'; -- MEZCLA ASFALTICA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_TRANSICION'; -- PIEDRA TRANSICION
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PRESTAMO_IMPORTADO'; -- PRESTAMO IMPORTADO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ARENA_DE_RIO'; -- ARENA DE RIO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ARENA_FINA'; -- ARENA FINA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'FRESADO'; -- FRESADO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ARENA_LISTA_PARA_HORMIGON'; -- ARENA LISTA PARA HORMIGON
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_BOLON'; -- PIEDRA BOLON
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'ESCOMBROS'; -- ESCOMBROS
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_3_4'; -- PIEDRA 3/4
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'BASALTO_SIN_CLASIFICAR'; -- BASALTO SIN CLASIFICAR
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'BASALTO_SAN_CARLOS'; -- BASALTO SAN CARLOS
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'CASCAJO'; -- CASCAJO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_HOMO_57'; -- PIEDRA HOMO #57
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_BLANCA'; -- PIEDRA BLANCA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'MEJORAMIENTO_CRIBADO'; -- MEJORAMIENTO CRIBADO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_7_8'; -- PIEDRA 7/8
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRAPLEN'; -- PIEDRAPLEN
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'TRITURADO_4_10'; -- TRITURADO 4-10
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'BASE_CEMENTO'; -- BASE CEMENTO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'MEJORAMIENTO_S_C'; -- MEJORAMIENTO S/C
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'CISCO_P_TUBERIA'; -- CISCO P/TUBERIA
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'CASCAJO_CRIBADO'; -- CASCAJO CRIBADO
ALTER TYPE "MaterialType" ADD VALUE IF NOT EXISTS 'PIEDRA_BASE'; -- PIEDRA BASE
